spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/db_meetingsapp_intershop
    username: cedric
    password: Gomo.2025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

